name = "WezTerm Default"
appearance = "dark"

[colors]
background    = "#141617"
foreground    = "#d5c4a1"
cursor        = "#52ad70"
cursor_text   = "#141617"
selection_bg  = "#27414d"
selection_fg  = "#d5c4a1"

[colors.ansi]
black   = "#000000"
red     = "#cc5555"
green   = "#55cc55"
yellow  = "#cdcd55"
blue    = "#5555cc"
magenta = "#cc55cc"
cyan    = "#7acaca"
white   = "#cccccc"

[colors.bright]
black   = "#555555"
red     = "#ff5555"
green   = "#55ff55"
yellow  = "#ffff55"
blue    = "#5555ff"
magenta = "#ff55ff"
cyan    = "#55ffff"
white   = "#ffffff"

[colors.tab]
bar_bg          = "#141617"
active_bg       = "#141617"
active_fg       = "#fabd2f"
inactive_bg     = "#141617"
inactive_fg     = "#928374"
hover_bg        = "#1c1f20"
hover_fg        = "#d5c4a1"
close_button_fg = "#ff5555"
