[package]
name = "sonicterm-render-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
license = "MIT OR Apache-2.0"

[lints]
workspace = true

[dependencies]
sonicterm-types = { workspace = true }
sonicterm-grid = { workspace = true }
sonicterm-cfg = { workspace = true }
sonicterm-ui = { workspace = true }
